version: "3.9"

services:
  web-service:
    container_name: web-server
    build: .
    image: ${IMAGE_WEB_SERVER}
    pull_policy: ${IMAGE_PULL_POLICY:-if_not_present}
    env_file:
      - "${ENV_FILE:-.env}"
    restart: always
    ports:
      - "8080:8080"
    networks:
      - rest
    depends_on:
      - redis

  redis:
    container_name: redis
    image: ${IMAGE_REDIS}
    pull_policy: ${IMAGE_PULL_POLICY:-if_not_present}
    env_file:
      - "${ENV_FILE:-.env}"
    restart: always
    command:
      [
          "redis-server",
          "--appendonly",
          "yes",
          "--requirepass",
          "${REDIS_PASSWORD}",
      ]
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - ${DATA_PATH}/.data/redis:/data
    environment:
      - TZ=${TIMEZONE}
    networks:
      - rest

networks:
  rest:
    name: redis-rest_default
    driver: bridge
