---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LeleUser.
--- DateTime: 2023/1/17 11:32
---
-- 1.先从缓存中取json字符串数据
local oldJsonStr = redis.call("get", KEYS[1])

-- 2.将取出的数据转成json

-- 3.将要设置的属性和参数存入json
-- 4.将设置好的json转string

-- 5.设置缓存
return redis.call("set", KEYS[1], newJsonStr)







